/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InsuredRouteImport } from './routes/insured'
import { Route as CpsdRouteImport } from './routes/cpsd'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuredRoute = InsuredRouteImport.update({
  id: '/insured',
  path: '/insured',
  getParentRoute: () => rootRouteImport,
} as any)
const CpsdRoute = CpsdRouteImport.update({
  id: '/cpsd',
  path: '/cpsd',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/cpsd': typeof CpsdRoute
  '/insured': typeof InsuredRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/cpsd': typeof CpsdRoute
  '/insured': typeof InsuredRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/cpsd': typeof CpsdRoute
  '/insured': typeof InsuredRoute
  '/news': typeof NewsRoute
  '/programs': typeof ProgramsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/cpsd'
    | '/insured'
    | '/news'
    | '/programs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/cpsd'
    | '/insured'
    | '/news'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/contact'
    | '/cpsd'
    | '/insured'
    | '/news'
    | '/programs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  CpsdRoute: typeof CpsdRoute
  InsuredRoute: typeof InsuredRoute
  NewsRoute: typeof NewsRoute
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insured': {
      id: '/insured'
      path: '/insured'
      fullPath: '/insured'
      preLoaderRoute: typeof InsuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpsd': {
      id: '/cpsd'
      path: '/cpsd'
      fullPath: '/cpsd'
      preLoaderRoute: typeof CpsdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  CpsdRoute: CpsdRoute,
  InsuredRoute: InsuredRoute,
  NewsRoute: NewsRoute,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
